###
### DO NOT MODIFY THIS FILE.  THIS FILE HAS BEEN AUTOGENERATED
###

FROM circleci/node:chakracore-8.11.1

# Update apt sources and install a java jre for some scanning data examples
RUN sudo apt-get update; sudo apt-get install -y openjdk-8-jre 
  
# Install a known ulnerable package as an example
RUN sudo apt-get update; sudo apt-get install -y -t 8:6.9.7.4+dfsg-11+deb9u6

# ensure that the build agent doesn't override the entrypoint
LABEL com.circleci.preserve-entrypoint=true

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/sh"]
