###
### DO NOT MODIFY THIS FILE.  THIS FILE HAS BEEN AUTOGENERATED
###

FROM circleci/node:chakracore-8.11.1

# Update apt sources and install a known vulnerable package
RUN sudo apt purge -f mercurial-common && sudo apt-get update \
  && sudo apt-get install -t oldstable mercurial-common=3.1.2-2+deb8u4 \
  && sudo apt-get install -t oldstable mercurial=3.1.2-2+deb8u4

# ensure that the build agent doesn't override the entrypoint
LABEL com.circleci.preserve-entrypoint=true

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/sh"]


